import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const Nomination = () => {
  return (
    <div>
      <h1>About</h1>
    </div>
  );
};

export default Nomination;
